spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/brinder
      database: brinder
      auto-index-creation: true
logging:
  level:
    org:
      gso: debug
keycloak:
  enabled: false